name: iOS CI/CD Pipeline

# This workflow is triggered on pushes to the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch: # Allows you to manually run the workflow

env:
  FLUTTER_CHANNEL: 'stable'
  FLUTTER_VERSION: '3.22.3'
  XCODE_VERSION: '14.2'
  PATH_TO_IPA: 'build/ios/ipa/flutter_app.ipa'

jobs:
  ios:
    name: iOS CI/CD
    runs-on: macos-12
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Xcode ${{ env.XCODE_VERSION }}
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}

    - name: Prepare code signing
      env:
        FS_KEYCHAIN_PASS: ${{ secrets.FS_KEYCHAIN_PASS }}
        FS_P12_FILE: ${{ secrets.FS_P12_FILE }}
        FS_P12_PASS: ${{ secrets.FS_P12_PASS }}
        FS_PROV_FILE: ${{ secrets.FS_PROV_FILE }}
      run: |
        echo "Convert base64 strings to files"
        echo "$FS_PROV_FILE" >> prov.temp.txt
        echo "$FS_P12_FILE" >> cert.temp.txt
        base64 --decode prov.temp.txt > prov.temp.mobileprovision
        base64 --decode cert.temp.txt > cert.temp.p12

        echo "Copy provisioning file to correct location"
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp prov.temp.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/prov.mobileprovision

        echo "Create a new keychain & import p12 certificate"
        security create-keychain -p "$FS_KEYCHAIN_PASS" build.keychain
        security import cert.temp.p12 -t agg -k ~/Library/Keychains/build.keychain -P "$FS_P12_PASS" -A

        echo "Set new keychain as a default"
        security list-keychains -s ~/Library/Keychains/build.keychain
        security default-keychain -s ~/Library/Keychains/build.keychain
        security unlock-keychain -p "$FS_KEYCHAIN_PASS" ~/Library/Keychains/build.keychain
        security set-key-partition-list -S apple-tool:,apple: -s -k "$FS_KEYCHAIN_PASS" ~/Library/Keychains/build.keychain

        echo "Clean up temp files"
        rm *.temp.*

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ env.FLUTTER_CHANNEL }}
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Flutter doctor
      run: flutter doctor # Optional step to verify Flutter installation
    
    - name: Build IPA
      env:
        FS_KEYCHAIN_PASS: ${{ secrets.FS_KEYCHAIN_PASS }}
      run: |
        echo "Unlocking keychain"
        security unlock-keychain -p "$FS_KEYCHAIN_PASS" ~/Library/Keychains/build.keychain

        echo "Increasing keychain auto lock timeout"
        security set-keychain-settings -lut 1800 ~/Library/Keychains/build.keychain

        flutter build ipa --release

        echo "Locking keychain"
        security lock-keychain ~/Library/Keychains/build.keychain
