on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.22.3"

    # Create a temporary keychain
    - name: Create a temporary keychain
      run: |
        security create-keychain -p "$IOS_GITHUB_KEYCHAIN_PASSWORD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$IOS_GITHUB_KEYCHAIN_PASSWORD" build.keychain
        security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
      env:
        IOS_GITHUB_KEYCHAIN_PASSWORD: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}

    # Import the distribution certificate
    - name: Import iOS distribution certificate
      run: |
        security import certs/ios_distribution.p12 -P "$IOS_BUILD_CERTIFICATE_PASSWORD" -k ~/Library/Keychains/build.keychain -A
        security set-key-partition-list -S apple-tool:,apple: -s -k "$IOS_GITHUB_KEYCHAIN_PASSWORD" ~/Library/Keychains/build.keychain
      env:
        IOS_BUILD_CERTIFICATE_PASSWORD: ${{ secrets.IOS_BUILD_CERTIFICATE_PASSWORD }}
        IOS_GITHUB_KEYCHAIN_PASSWORD: ${{ secrets.IOS_GITHUB_KEYCHAIN_PASSWORD }}

    # Install provisioning profile
    - name: Install provisioning profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp certs/provisioning.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

    # Build and sign the iOS app
    - name: Build iOS app
      run: |
        flutter build ios --release --no-codesign
        xcodebuild \
          -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -archivePath build/Runner.xcarchive archive

    - name: Export IPA
      run: |
        xcodebuild \
          -exportArchive \
          -archivePath build/Runner.xcarchive \
          -exportOptionsPlist ios/GithubActionsExportOptions.plist \
          -exportPath build/Runner.ipa
