name: Build and distribute

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3.6
        with:
          flutter-version: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Install the Apple certificate and provisioning profile
        env:
          DISTRIBUTION_P12: ${{ secrets.DISTRIBUTION_P12 }}
          P12_PASS: ${{ secrets.P12_PASS }}
          PROD_PROVISION: ${{ secrets.PROD_PROVISION }}
          
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12

          PP_PATH=$RUNNER_TEMP/prov.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo -n "$DISTRIBUTION_P12" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$PROD_PROVISION" | base64 --decode -o $PP_PATH

          # import certificate and provisioning profile from secrets
          security create-keychain -p "$P12_PASS" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$P12_PASS" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASS" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$P12_PASS" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles 
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Build iOS
        run: flutter build ipa --export-options-plist=ExportOptions.plist
