name: Build and Deploy iOS App

on:
  push:
    branches:
      - master  # Trigger this workflow on push to the master branch

jobs:
  build:
    runs-on: macos-latest  # GitHub's macOS runners

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS app
      run: flutter build ios --release --no-codesign

    - name: Set up code signing
      run: |
        echo "${{ secrets.CERTIFICATE_BASE64 }}" | base64 --decode > certificate.p12
        echo "${{ secrets.PROFILE_BASE64 }}" | base64 --decode > profile.mobileprovision

        # Create and unlock keychain
        security create-keychain -p "" build.keychain
        security import certificate.p12 -k ~/Library/Keychains/build.keychain -P "${{ secrets.CERTIFICATE_PASSWORD }}" -A
        security unlock-keychain -p "" ~/Library/Keychains/build.keychain
        security set-keychain-settings -t 3600 -u ~/Library/Keychains/build.keychain

        # Install provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

    - name: Export IPA
      run: |
        xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration AppStoreDistribution archive -archivePath ios/build/Runner.xcarchive -allowProvisioningUpdates
        xcodebuild -exportArchive -archivePath ios/build/Runner.xcarchive -exportOptionsPlist ios/Runner/ExportOptions.plist -exportPath ios/build

    - name: Upload to App Store
      run: |
        xcrun altool --upload-app --type ios --file ios/build/Runner.ipa --username ${{ secrets.APP_STORE_CONNECT_USERNAME }} --password ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
